name: Ping SocialGeek Cron

on:
  schedule:
    - cron: "*/2 * * * *"   # run every 2 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Cron URL
        run: |
          curl -s "https://crm.socialgeekbd.com/cron/index"
